### ISSUE TITLE
mpirun issue

### ISSUE THREAD

**Issue by guannant** [ExascaleAM/AdditiveFOAM#1]
Hi there, I installed AdditiveFOAM with Spack as instructed but am still not able to run the tutorial files. I keep getting something like "foamDirectory: command not found", shown in the screenshot below. I have put the right path to OpenFOAM lirary in the ALLrun file, not sure why this is still happenning. Is there any document anyone can provide to show how to setup the necessary file path?

<img width="634" alt="image" src="https://github.com/ExascaleAM/AdditiveFOAM/assets/57839515/78d438e2-efb9-4711-b21d-c1e7df2a7046">

**Comment by streeve** [comment]
@colemanjs any ideas here?
